services:
  postgres:
    image: postgres:14.23-alpine3.24
    container_name: egotibi-postgres
    environment:
      - DB_USERNAME=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  # rabbitmq:
  #   image: rabbitmq:3-management
  #   container_name: egotibi-rabbitmq
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"