spring.application.name=ticketservice

# postgres configurations
spring.datasource.url=jdbc:${POSTGRES_URI}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configurations
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.rabbitmq.host=${RABBIT_MQ_HOST}
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBIT_MQ_USERNAME}
spring.rabbitmq.password=${RABBIT_MQ_PASSWORD}